name: Publish NPM Package

on:
  workflow_call:
    secrets:
      npm_token:
        required: true
      gh_token:
        required: true

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - run: git config user.email "scottwestover2006@gmail.com"
      - run: git config user.name "@github-ci"
      - run: yarn version --patch --message "Bump version to %s"

      - run: git push
      - run: git push --follow-tags

      - name: build project
        run: npm run build

      - name: publish to npm
        run: |
          npm set //registry.npmjs.org/:_authToken ${{ secrets.npm_token }}
          npm run publish:npm

      - name: publish to github
        run: |
          npm config set registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.gh_token }}
          npm run publish:github
